<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_glue-modal__close-btn gfe-modal__clo_487e1b</name>
   <tag></tag>
   <elementGuidId>068b4a1a-5101-4655-b037-23e2ea9ab9c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[3]/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.glue-modal__close-btn.gfe-modal__close-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d04504f7-9dee-4410-b9c9-3a7dbeb505ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>glue-modal__close-btn gfe-modal__close-button</value>
      <webElementGuid>863eab82-f9fd-41c5-af9e-3b42ce238e6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>042dadce-a1c9-460f-8c51-ea463f079f8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;gfe-main&quot;]/body[@class=&quot;gfe-page-body classroom ready glue-mod-no-scroll&quot;]/div[@class=&quot;gfe-modal glue-modal glue-modal--dark gfe-modal--dark-mode gfe-modal--geolocation glue-modal-open&quot;]/div[@class=&quot;gfe-modal__content-wrapper&quot;]/button[@class=&quot;glue-modal__close-btn gfe-modal__close-button&quot;]</value>
      <webElementGuid>ef23934e-ef47-4761-b874-3b7a2a34139c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/button</value>
      <webElementGuid>f0458df5-a1ab-429c-9051-a15a9c499ffe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
