<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_reg.pbru.ac.th  register</name>
   <tag></tag>
   <elementGuidId>98937275-5fe3-49cc-9575-8a246baedd8e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='web']/ol/li/div/div/h3/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7ad1feac-d921-4303-b990-216b0ae37c2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> d-ib fz-20 lh-26 td-hu tc va-bot mxw-100p</value>
      <webElementGuid>cc29dc0b-c056-4904-9d83-0998f8492dec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-matarget</name>
      <type>Main</type>
      <value>algo</value>
      <webElementGuid>41ecc19b-4fb4-45d9-9edf-e78f3df5397d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://reg.pbru.ac.th/register/</value>
      <webElementGuid>10dfb65d-217c-47c3-824d-88d96eac182a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>referrerpolicy</name>
      <type>Main</type>
      <value>origin</value>
      <webElementGuid>6d4bf69d-a8f7-4438-b95c-2e74aa608675</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>9b76998f-fd55-4e73-ab62-da5f311a6fee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-0b2</name>
      <type>Main</type>
      <value>65a633a3b8c27</value>
      <webElementGuid>7303246c-c6a2-441b-b70e-840ceca1ddf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>ระบบบริการการศึกษา มหาวิทยาลัยราชภัฏเพชรบุรี</value>
      <webElementGuid>7c17cbd4-a6f2-4b76-9f4c-af069f66bfbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>reg.pbru.ac.th › registerระบบบริการการศึกษา มหาวิทยาลัยราชภัฏเพชรบุรี</value>
      <webElementGuid>a614af37-feb4-4212-942d-f474c24306c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;web&quot;)/ol[@class=&quot;reg searchCenterMiddle&quot;]/li[@class=&quot;first&quot;]/div[@class=&quot;dd algo algo-sr relsrch fst Sr&quot;]/div[@class=&quot;compTitle options-toggle&quot;]/h3[@class=&quot;title&quot;]/a[@class=&quot;d-ib fz-20 lh-26 td-hu tc va-bot mxw-100p&quot;]</value>
      <webElementGuid>06d952c2-6042-4c72-a81c-9b158e1cd35f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='web']/ol/li/div/div/h3/a</value>
      <webElementGuid>010216a3-9321-4c4b-b3c0-8bb8a108dc92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://reg.pbru.ac.th/register/')]</value>
      <webElementGuid>c8702355-339b-43db-9f0f-641176782a16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3/a</value>
      <webElementGuid>ae56c0e3-68a4-4e62-808c-96e60b4bd845</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://reg.pbru.ac.th/register/' and (text() = 'reg.pbru.ac.th › registerระบบบริการการศึกษา มหาวิทยาลัยราชภัฏเพชรบุรี' or . = 'reg.pbru.ac.th › registerระบบบริการการศึกษา มหาวิทยาลัยราชภัฏเพชรบุรี')]</value>
      <webElementGuid>029bd8c5-3c47-4b5b-8561-bc9de9c070f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
