<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_</name>
   <tag></tag>
   <elementGuidId>12f7cdb7-8a9e-4115-af56-9872ea711825</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gb']/div/div[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.gb_Aa.gb_kd.gb_Md.gb_le</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a09a37bd-5758-4cf6-9f09-51e72edcf49e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gb_Aa gb_kd gb_Md gb_le</value>
      <webElementGuid>eece4d98-e4a4-495e-9b62-04c40b229f72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>เข้าสู่ระบบ</value>
      <webElementGuid>801fc343-f190-47df-b1dd-735b197756f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://accounts.google.com/ServiceLogin?hl=th&amp;passive=true&amp;continue=https://www.google.com/&amp;ec=GAZAmgQ</value>
      <webElementGuid>638190ec-8924-4e0d-ba95-f7a72b566047</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_top</value>
      <webElementGuid>a73decbf-5b75-4889-bfe6-a1802e7a085d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>เข้าสู่ระบบ</value>
      <webElementGuid>239a40c7-cb51-4989-8f67-adc600ea5479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gb&quot;)/div[@class=&quot;gb_zd gb_db gb_od&quot;]/div[@class=&quot;gb_Td&quot;]/a[@class=&quot;gb_Aa gb_kd gb_Md gb_le&quot;]</value>
      <webElementGuid>6c335d14-f4ee-4296-936e-60856fd9c901</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gb']/div/div[2]/a</value>
      <webElementGuid>66227412-bb93-4806-9dd9-69c4721d129b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://accounts.google.com/ServiceLogin?hl=th&amp;passive=true&amp;continue=https://www.google.com/&amp;ec=GAZAmgQ')]</value>
      <webElementGuid>de8caa32-4166-44a5-a383-ae5f1194db50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>78f84408-5309-4c49-aa19-530c5d657f35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://accounts.google.com/ServiceLogin?hl=th&amp;passive=true&amp;continue=https://www.google.com/&amp;ec=GAZAmgQ' and (text() = 'เข้าสู่ระบบ' or . = 'เข้าสู่ระบบ')]</value>
      <webElementGuid>9649e63a-19c9-4949-8504-1731215644dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
