<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_CcAdNbmarginauto.QCzoEcmargin-top3pxcol_88446e</name>
   <tag></tag>
   <elementGuidId>a869089e-31fc-429a-847e-ce6396125401</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form/div/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.iblpc</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>db966550-cbcf-4c37-a206-903d0c17c75f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iblpc</value>
      <webElementGuid>bc2d1334-09c6-48e4-afa6-394803b38434</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsname</name>
      <type>Main</type>
      <value>uFMOof</value>
      <webElementGuid>7f6d885e-eac7-4971-964e-1cee2d04c647</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>.CcAdNb{margin:auto}.QCzoEc{margin-top:3px;color:#9aa0a6}</value>
      <webElementGuid>def761df-7238-4460-bfa0-430e980ba1fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;L3eUgb&quot;]/div[@class=&quot;o3j99 ikrT4e om7nvf&quot;]/form[1]/div[1]/div[@class=&quot;A8SBwf emcav&quot;]/div[@class=&quot;RNNXgb&quot;]/div[@class=&quot;SDkEP&quot;]/div[@class=&quot;iblpc&quot;]</value>
      <webElementGuid>4cae6fd0-1842-43be-9d05-0884de2ed650</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/div</value>
      <webElementGuid>9e62e9ac-3fdb-47e2-8487-8b3ff0e6c3c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '.CcAdNb{margin:auto}.QCzoEc{margin-top:3px;color:#9aa0a6}' or . = '.CcAdNb{margin:auto}.QCzoEc{margin-top:3px;color:#9aa0a6}')]</value>
      <webElementGuid>b6e91396-2384-4fba-a433-b324d92b7a0e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
