<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_</name>
   <tag></tag>
   <elementGuidId>3f799372-eea8-4a52-a5f7-5cc6dab4019a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='c7mM1c']/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#c7mM1c > div.ClJ9Yb</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>36ba570f-84a0-4b5e-bbeb-bc5114f787c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ClJ9Yb</value>
      <webElementGuid>7e81a023-e6ac-478f-adae-2b4ab59f83a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>0cc19cb1-00a5-467c-96ae-b65ebe396ad8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>เพลง</value>
      <webElementGuid>bcf53861-06ff-4135-b087-54c4a6829661</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c7mM1c&quot;)/div[@class=&quot;ClJ9Yb&quot;]</value>
      <webElementGuid>184a2b98-b86d-473c-b80a-5d06a9f30747</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='c7mM1c']/div[2]</value>
      <webElementGuid>f8aa11cb-063e-43f0-9b7b-32e219e956ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul/li[3]/div/div[2]/div/div[2]</value>
      <webElementGuid>0d3578c7-53fa-4d77-9529-7577d1091d0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'เพลง' or . = 'เพลง')]</value>
      <webElementGuid>8254bb3b-d610-4401-accb-7ce4f39d23d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
