<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_</name>
   <tag></tag>
   <elementGuidId>bab03507-5743-4bc3-a730-b259b1088595</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gb']/div/div[2]/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.gb_Id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>acf1efa1-018d-4756-bde3-54476fb1be52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gb_Id</value>
      <webElementGuid>3a3c01d3-bc41-4dc1-9bf6-ca50a54a217b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>เข้าสู่ระบบ</value>
      <webElementGuid>7ad2a82d-cbbb-44bf-aa9f-8cc881c7e079</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gb&quot;)/div[@class=&quot;gb_zd gb_db gb_od&quot;]/div[@class=&quot;gb_Td&quot;]/a[@class=&quot;gb_Aa gb_kd gb_Md gb_le&quot;]/span[@class=&quot;gb_Id&quot;]</value>
      <webElementGuid>9dfd68db-5a27-4807-ac38-3e9fb974e38e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gb']/div/div[2]/a/span</value>
      <webElementGuid>df28f44e-20d8-435d-9f55-5c55ae3266b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>df88eeca-8afc-4a66-96bf-2432fe649934</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'เข้าสู่ระบบ' or . = 'เข้าสู่ระบบ')]</value>
      <webElementGuid>c907a058-f428-4be3-bd3f-95b58c20d1c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
