<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_www.krurestaurant.comKru Contemporary Jap_3946b9</name>
   <tag></tag>
   <elementGuidId>c719e47b-0578-43df-8be5-b914089c4988</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='web']/ol/li/div/div/h3/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7dafef60-b24b-4590-90e1-8835814f2f82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> d-ib fz-20 lh-26 td-hu tc va-bot mxw-100p</value>
      <webElementGuid>853ed203-a5e0-4d2c-ba58-df2033b54347</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-matarget</name>
      <type>Main</type>
      <value>algo</value>
      <webElementGuid>9ff68556-3e41-4a93-8685-8b7ff7504b76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.krurestaurant.com/</value>
      <webElementGuid>f8907bba-a7bf-4b8f-b6d5-20ff299cc68a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>referrerpolicy</name>
      <type>Main</type>
      <value>origin</value>
      <webElementGuid>112b46e2-35d7-407b-971b-56a776708f7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>010baa1b-f3ab-44aa-897f-4024e7358bd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-f1f</name>
      <type>Main</type>
      <value>65a636b9ed5ea</value>
      <webElementGuid>0ab11d6a-624c-43e9-a0e9-b6160ce7c44a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Kru Contemporary Japanese Cuisine</value>
      <webElementGuid>cde71b46-441b-494c-a251-0bda5f02fc5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>www.krurestaurant.comKru Contemporary Japanese Cuisine</value>
      <webElementGuid>d09d2a84-e7c1-4c8d-a209-cb7b1c125630</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;web&quot;)/ol[@class=&quot;reg searchCenterMiddle&quot;]/li[@class=&quot;first&quot;]/div[@class=&quot;dd algo algo-sr relsrch fst richAlgo&quot;]/div[@class=&quot;compTitle options-toggle&quot;]/h3[@class=&quot;title&quot;]/a[@class=&quot;d-ib fz-20 lh-26 td-hu tc va-bot mxw-100p&quot;]</value>
      <webElementGuid>c2f15333-54ca-4def-a74f-8b43a1a6dae3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='web']/ol/li/div/div/h3/a</value>
      <webElementGuid>2629e886-072a-4d14-a6f7-81a0efd355ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.krurestaurant.com/')]</value>
      <webElementGuid>b17039ff-c8f0-4e87-9f24-6884f65e23ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3/a</value>
      <webElementGuid>4a37da39-bf77-4eef-8957-cc9d202a4d16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.krurestaurant.com/' and (text() = 'www.krurestaurant.comKru Contemporary Japanese Cuisine' or . = 'www.krurestaurant.comKru Contemporary Japanese Cuisine')]</value>
      <webElementGuid>5fe427a0-21ee-42e0-9685-baecd4b6a93c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
